export const CONNECT_USER_START = 'CONNECT_USER_START';
export const CONNECT_USER_SUCCESS = 'CONNECT_USER_SUCCESS';
export const CONNECT_USER_ERROR = 'CONNECT_USER_ERROR';
export const UPDATE_USER_BALANCE = 'UPDATE_USER_BALANCE';
